### ISSUE TITLE
Circular Reference Error

### ISSUE THREAD

**Issue by ialex** [Rootbuzz/JSONate#5]
I was trying to jsonate a raw query but i received a circular reference error i solved my looping the items on raw query like this:

sql = ('SELECT * FROM memes_meme ORDER BY ranking(id, upvotes, 3) DESC '
           'OFFSET %s LIMIT %s;') % (offset + 1, limit)
memes = map(jsonate, Meme.objects.raw(sql))

is there another way to make the raw query to work didnt dig too much why i was receiving the Circular reference.

**Comment by jiaaro** [comment]
I think jsonate doesn't know how to handle a raw queryset, but you could implement support for it if you wanted:

```
from jsonate.json_encoder import register_typemap

@register_typemap(RawQuerySet)
def map_raw_queryset(obj):
    return list(obj)
```

I have a feeling the issue is cropping up here though: https://github.com/Rootbuzz/JSONate/blob/master/jsonate/json_encoder.py#L80 

so maybe just implementing a `YourModel.to_json` method would get the job done?

**Comment by ialex** [comment]
I already have the to_json inside my model but still shows the Circular reference error i will try adding the new typemap and send PR

**Comment by jiaaro** [comment]
since `map()` worked, an alternative workaround that will probably also work is:

```python
jsonate(list(your_raw_queryset))
```

**Comment by ialex** [comment]
That worked perfectly thanks
